src/actions/index.js
src/stores/FacetsStore.js
src/stores/SearchStore.js
src/stores/index.js
storefront/resources/facets.json
storefront/resources/products.json

Cria FacetsStore

---

src/StorefrontSDK.js
src/actions/CartActions.js
src/index.js
src/services/Checkout.js
src/services/Search.js
src/stores/CartStore.js
src/stores/CategoryStore.js
src/stores/ComponentStore.js
src/stores/FacetsStore.js
src/stores/ProductStore.js
src/stores/ResourceStore.js
src/stores/SearchStore.js
src/utils/connectToStores.js
src/utils/editable.js
webpack.config.js

Stop exposing lodash, adding the whole library makes the bundle too big.

Dont expose lodash

---

package.json
src/App.js
src/StorefrontSDK.js
src/utils/connectToStores.js
src/utils/editable.js
storefront/layout.html
webpack.config.js

- Place it inside an utils object
- Make it follow the good practices: just trigger a change if a **piece** of the store that the component is interested changes
- Use PureRenderMixin: huge gain of performance here, only re-render if the piece of the store (cited above) changes

New connectToStores

---

src/stores/CategoryStore.js

@brenoc I'm not used to ImmutableJS, is it okay to use `.toJS()` like this?

Add getCategory for CategoryStore

---

src/stores/FacetsStore.js

Removed unused function, deep Immutable state and minor changes.

Deep Immutable + minor changes on Facets Store

---

src/actions/SearchActions.js
src/stores/ProductStore.js
src/stores/SearchStore.js

Use immutable objects for caching search requests.

Add nice cache for SearchStore

---

src/StorefrontSDK.js
src/utils/Img.js
src/utils/Price.js

Those components are going to be used everywhere. Let's share them.

Add Price and Img components to SDK utils

---

meta.json

This should be done in all the storefront apps.

Add storefront as a dependency

---

storefront/resources/products.json

Add pagination queries for products resource

---

src/actions/ResourceActions.js
src/services/Storefront.js

Add query for ResourceAction + Storefront service

---

webpack.config.js

Reduce libs build size from 322kb to 259kb

Add DefinePlugin

---

storefront/resources/facets.json
storefront/resources/products.json

Add query parameters for facets and products!

New resources parameters

---

package.json
src/StorefrontSDK.js
src/actions/CartActions.js
src/index.js
src/services/Checkout.js
src/services/Search.js
src/stores/CartStore.js
src/stores/CategoryStore.js
src/stores/ComponentStore.js
src/stores/FacetsStore.js
src/stores/ProductStore.js
src/stores/ResourceStore.js
src/stores/SearchStore.js
src/utils/connectToStores.js
src/utils/editable.js

Fix lodash usage

---

src/stores/SearchStore.js

At least for the case of `ExhibitionMode` component, makes navigation work much better!

Use path and componentId as map keys

---

package.json
src/StorefrontSDK.js
webpack.config.js

Add and expose css-transition-group

---

package.json
storefront/layout.html
webpack.config.js

Oh yeah, green field now to add debugging messages.

Create dev and production build

---

src/services/Storefront.js

@brenoc @bellacorbo @brunoabreu Title says it all!

Fix service queries and URLs

---

src/stores/FacetsStore.js

Add check for resource if undefined

---

.babelrc
.eslintrc
package.json
src/StorefrontSDK.js
src/actions/AreaActions.js
src/actions/index.js
src/services/Storefront.js
src/stores/AssetStore.js
src/stores/CategoryStore.js
src/stores/FacetsStore.js
src/stores/ProductStore.js
src/stores/ResourceStore.js
src/stores/SearchStore.js
src/stores/SettingsStore.js
src/stores/index.js
src/utils/loadPage.js

Breaking changes:
- Rename ResourceActions to AreaActions
Features:
- Expose Storefront service at `storefront.sdk.services.storefront`
- Load assets async
- New store: AssetStore

Load assets async

---

src/actions/ContextActions.js
src/stores/ContextStore.js
src/utils/loadPage.js

This PR exposes the page loading via a key on the ContextStore state.

Expose page load via ContextStore

---

src/dispatcher/StorefrontDispatcher.js

Title says it all!
@breno @amoreira

Add check to only put Alt debug on dev mode

---

src/StorefrontSDK.js
src/actions/AreaActions.js
src/actions/ContextActions.js
src/components/Img.js
src/components/Root.js
src/services/Storefront.js
src/stores/AssetStore.js
src/stores/ContextStore.js
src/stores/ResourceStore.js
src/utils/loadPage.js

This PR optimizes SDK loading by removing unnecessary requests on load and adding some caches.
Plus some minor fixes

Optimize load

---

src/components/Root.js

This class is supposed to be a contextual wrapper to some styles in the theme, so it _only_ affects the theme, but not the Editor UI.
Due to architecture changes throughout the project, now it wraps the editor as well, so I'm taking this class there.
Pls review

[Review] Remove theme class
